# Generated by Django 4.2.11 on 2024-04-18 20:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("descricao", ckeditor.fields.RichTextField()),
                (
                    "criador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atividade",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", ckeditor.fields.RichTextField()),
                ("data_entrega", models.DateField()),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="galeria.grupo"
                    ),
                ),
            ],
        ),
    ]
